- name: Deploy ifup-pre-local (CentOS/RHEL)
  copy:
    src: ifup-pre-local
    dest: /sbin
    mode: 0755

- name: Dumping value of sp_disable_nm
  debug:
    var: sp_disable_nm
    verbosity: 2
  when: sp_disable_nm is defined

- name: Determining whether to disable NetworkManager
  set_fact:
    disable_nm: "{{ sp_disable_nm | bool if sp_disable_nm is defined else redhat_disable_nm_map[ansible_distribution_major_version] | bool }}"

- name: Configuring the NetworkManager service
  systemd:
    name: NetworkManager
    state: "{{ disable_nm | ternary ('stopped', 'started') }}"
    enabled: "{{ not disable_nm }}"

- name: Installing network-scripts (CentOS 8/RHEL 8)
  yum:
    name: network-scripts
    state: present
  when:
    - disable_nm
    - ansible_distribution_major_version | int == 8

- name: Enabling network-scripts on CentOS
  systemd:
    name: network
    enabled: "{{ disable_nm }}"
