#!/usr/bin/env ansible-playbook

- name: "Reboot host and wait it to restart"
  gather_facts: false
  hosts: storpool
  become: yes
  serial: 1
  tasks:
    - reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 10
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: sp_reboot | bool | default(false)
