---
- name: Creating StorPool tools directory
  file:
    path: "{{ sp_toolsdir }}"
    state: directory

- name: Creating StorPool system directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/storpool
    - /etc/storpool.conf.d
    - /etc/cgconfig.d
    - /usr/lib/storpool
