---
- name: Increase crashkernel size (Debian/Ubuntu)
  become: true
  shell: |
    echo "GRUB_CMDLINE_LINUX_DEFAULT=\"\$GRUB_CMDLINE_LINUX_DEFAULT crashkernel=512M"\" > /etc/default/grub.d/kdump-tools.cfg
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Run patchkdumptools (Debian/Ubuntu)
  become: true
  command: "{{ sp_patchkdumptools }}"
  changed_when: false

- name: Update GRUB (Debian/Ubuntu)
  become: true
  command: update-grub2
  changed_when: false
