---
- name: Define sp_release_method
  import_tasks: "subtasks/sp_release_method.yml"

- name: Get StorPool packages
  import_tasks: "subtasks/get_storpool/storpool_{{ sp_release_method | default('web') }}.yml"

- name: Install StorPool modules
  become: true
  command:
    cmd: >-
      {{ sp_install_helper }}
      -g {{ sp_release | quote }}
      {{ '-r' if sp_reinstall else '' }}
      -w {{ sp_toolsdir | quote }}
      -m {{ sp_install_services | quote }}
      {% if sp_retry_install %}
      --retry 2
      {% endif %}
    chdir: "{{ sp_toolsdir }}"
  async: 1000
  poll: 0
  register: storpool_modules_sleeper
  changed_when: false

- name: Install StorPool modules - check on async task
  async_status:
    jid: "{{ storpool_modules_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 5
  changed_when: false
