---
- name: Include pre-installation tasks (Install Storpool)
  import_tasks: "pre-install.yml"

- name: Include installation tasks (Install Storpool) 
  include_tasks: "install-storpool.yml"

- name: Include post-installation tasks (Install Storpool) 
  include_tasks: "post-install.yml"

- name: Flush handlers
  meta: flush_handlers
