---
- name: Copying storpool.conf
  become: true
  copy:
    src: "{{ sp_config }}"
    dest: /etc/
  tags:
    - copy-storpool-conf

- name: Create dirs
  import_tasks: "subtasks/create_directories.yml"

- name: Install support tools
  import_tasks: "subtasks/support_tools.yml"
  when:
    - sp_poli is defined and
      sp_poli | bool
  tags:
    - install_support_tools

- name: Test memory
  import_tasks: "subtasks/test_memory.yml"
  when:
    - sp_vm is defined and
      not sp_vm | bool
  tags:
    - test_memory
