---
# tasks file for configure-cgroups
- name: Checking if StorPool cgroup configuration exists
  stat:
    path: /etc/cgconfig.d/storpool.slice.conf
  register: sp_slice_conf_file

- name: Checking if the kernel has memory swap cgroup enabled
  stat:
    path: /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
  register: cgroup_memsw_file

- name: Setting set_memsw fact
  set_fact:
    sp_cg_set_memsw: "{{ '1' if cgroup_memsw_file.stat.exists else '0' }}"
    cacheable: true

- name: Generating cgroup configuration files
  command:
    argv:
      - "{{ sp_cgtool_bin }}"
      - "{{ 'conf' + (' ' + cg_conf_extra if cg_conf_extra is defined else '' ) }}"
      - "SET_MEMSW={{ sp_cg_set_memsw }}"
  when: not sp_slice_conf_file.stat.exists
  notify: "start cgconfig"

- name: Migrating cgroup configuration
  command:
    argv:
      - "{{ sp_cgtool_bin }}"
      - "{{ 'conf -M -E' + (' ' + cg_conf_extra if cg_conf_extra is defined else '' ) }}"
      - "SET_MEMSW={{ sp_cg_set_memsw }}"
  when: sp_slice_conf_file.stat.exists
