---
- name: Deploy ifup-pre-local (CentOS/RHEL)
  copy:
    src: ifup-pre-local
    dest: /sbin
    mode: 0755

- name: Installing network-scripts on EL 8
  become: yes
  ansible.builtin.dnf:
    name: network-scripts
    state: present
  when:
    - ( ansible_distribution_major_version | int ) == 8
    - not sp_nm_controlled
  notify:
    - Installed network-scripts

- name: Installing network-scripts wrapper on EL 9
  become: yes
  ansible.builtin.dnf:
    name: NetworkManager-initscripts-updown
    state: present
  when:
    - ( ansible_distribution_major_version | int ) == 9

- name: Disabling NetworkManager
  become: yes
  ansible.builtin.systemd:
    name: NetworkManager
    state: stopped
    enabled: no
  when:
    - sp_disable_nm
    - ansible_facts.services["NetworkManager.service"] is defined
    - ansible_facts.services["NetworkManager.service"]["status"] != "not-found"
    - ( ansible_distribution_major_version | int ) <= 8
