---
# handlers file for configure-cgroups
- name: Enabling cgconfig
  become: true
  service:
    name: cgconfig
    enabled: true
  listen: "start cgconfig"

- name: Restarting cgconfig on EL systems
  become: true
  systemd:
    name: cgconfig
    state: restarted
  listen: "start cgconfig"
  when:
    - sp_cg_start_cgconfig
    - ansible_os_family == "RedHat"

- name: Restarting cgconfig on Debian-based systems
  become: true
  command: "/usr/bin/cgconfig-startup-systemd start"
  environment:
    CGCONFIG_FORCE_STARTUP: 1
  listen: "start cgconfig"
  when:
    - sp_cg_start_cgconfig
    - ansible_os_family == "Debian"
