- name: Installing specific kernel version
  become: yes
  ansible.builtin.package:
    name: "{{ kernel_package_name[(ansible_os_family | lower)] }}-{{ sp_kernel_version }}"
    state: present
  vars:
    kernel_package_name:
      redhat: kernel
      debian: linux-image
  when:
    - "'proxmox_hv' not in group_names"

- name: Installing specific kernel version on PVE 7
  become: yes
  ansible.builtin.package:
    name: "pve-kernel-{{ sp_kernel_version }}"
    state: present
  when:
    - "'proxmox_hv' in group_names"
    - (ansible_distribution_major_version | int) == 11

- name: Installing specific kernel version on PVE 8 and above
  become: yes
  ansible.builtin.package:
    name: "proxmox-kernel-{{ sp_kernel_version }}"
    state: present
  when:
    - "'proxmox_hv' in group_names"
    - (ansible_distribution_major_version | int) >= 12

- name: Installing extra kernel modules package on Ubuntu systems
  become: yes
  ansible.builtin.apt:
    name: "linux-modules-extra-{{ sp_kernel_version }}"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
