---
- name: Upgrade all packages (Ubuntu/Debian)
  apt:
    upgrade: full
    update_cache: true
  register: result
  until: result is success
  retries: 30
  delay: 10
  when:
    - sp_update_system is defined
    - sp_update_system | bool

- name: Install specified kernel
  apt:
    pkg:
      - "linux-image-{{ sp_kernel_version }}"
    update_cache: yes
  when:
    - sp_kernel_version is defined
    - not ansible_kernel | regex_search("^" + sp_kernel_version)

- name: Install extra kernel modules
  apt:
    pkg:
      - "linux-modules-extra-{{ sp_kernel_version }}"
    update_cache: yes
  when:
    - ansible_distribution == "Ubuntu"
    - sp_kernel_version is defined
    - not ansible_kernel | regex_search("^" + sp_kernel_version)

- name: Include tasks for setting default kernel
  include_tasks: "kernel.yml"

- name: Install HV dependencies (Ubuntu/Debian)
  apt:
    name: systemd-container
    update_cache: true
  when:
    - sp_roles.client is defined
    - sp_roles.client | bool
