---
- name: Upgrade all packages (Ubuntu/Debian)
  apt:
    upgrade: full
    update_cache: true
  register: result
  until: result is success
  retries: 30
  delay: 10
  when:
    - sp_update_system is defined
    - sp_update_system | bool

- name: Install HV dependencies (Ubuntu/Debian)
  apt:
    name: systemd-container
    update_cache: true
  when:
    - sp_roles.client is defined
    - sp_roles.client | bool
