- name: Make specified kernel the default on boot
  script: "files/set_default_kernel {{ sp_kernel_version }}"
  when:
    - sp_kernel_version is defined
    - not ansible_kernel | regex_search("^" + sp_kernel_version)

- name: Reboot host to apply specified kernel
  reboot:
    msg: Reboot initiated by Ansible
    connect_timeout: 10
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when:
    - sp_kernel_version is defined
    - not ansible_kernel | regex_search("^" + sp_kernel_version)

# Not using ansible_kernel since the value does not update after reboot
- name: Get current kernel
  command: "uname -r"
  register: uname
  when: sp_kernel_version is defined

- name: Verify we are using the specified kernel
  assert:
    that:
      - uname.stdout | regex_search("^" + sp_kernel_version)
    success_msg: "Running expected kernel {{ sp_kernel_version }}"
    fail_msg: "Running unexpected kernel {{ uname.stdout }}"
  when: sp_kernel_version is defined