---
- name: Configure mcelog (AlmaLinux)
  block:
    - name: Check if AMD processor
      command: "grep -q AMD /proc/cpuinfo"
      ignore_errors: true
      failed_when: false
      changed_when: false
      register: is_amd
    - name: Start and enable mcelog on boot (AlmaLinux)
      service:
        name: "mcelog"
        enabled: true
        state: started
      register: mcelog_service_status
      failed_when:
        - mcelog_service_status is failed
        - not ('Could not find the requested service' in mcelog_service_status.msg)
      when:
        - is_amd.rc == 1

- name: Configure tuned (AlmaLinux)
  block:
    - name: Start and enable tuned on boot (AlmaLinux)
      service:
        name: "tuned.service"
        enabled: true
        state: started
      register: tuned_service_status
      failed_when:
        - tuned_service_status is failed
        - not ('Could not find the requested service' in tuned_service_status.msg)
    - name: Get tuned profile
      command: "/usr/sbin/tuned-adm active"
      register: tuned_active
      changed_when: false
    - name: Set tuned profile
      command: "/usr/sbin/tuned-adm profile {{ tuned_profile }}"
      changed_when: false
      when:
        - tuned_profile not in tuned_active.stdout

- name: Configure firewall (AlmaLinux)
  block:
    - name: Disable firewalld service (AlmaLinux)
      systemd:
        name: "firewalld.service"
        enabled: false
        state: stopped
      register: fw_service_status
      failed_when:
        - fw_service_status is failed
        - not ('Could not find the requested service' in fw_service_status.msg)
      when:
        - sp_disable_fw is defined
        - sp_disable_fw | bool
    - name: Add StorPool ports to firewall - 81,3749,47567/TCP (AlmaLinux)
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        immediate: true
        state: enabled
      ignore_errors: true
      with_items: "{{ sp_fw_ports }}"
      when:
        - sp_disable_fw is defined
        - not sp_disable_fw | bool

- name: Disable NetworkManager (AlmaLinux)
  service:
    name: "NetworkManager.service"
    enabled: false
    state: stopped
  register: nm_service_status
  failed_when:
    - nm_service_status is failed
    - not ('Could not find the requested service' in nm_service_status.msg)
  when:
    - sp_disable_nm is defined
    - sp_disable_nm | bool

- name: Configure SELinux (AlmaLinux)
  selinux:
    state: "{{ sp_selinux | default('disabled') }}"
    policy: targeted
  ignore_errors: true
  vars:
    selinux_states:
      - permissive
      - disabled
  when:
    - sp_selinux is defined
    - sp_selinux in selinux_states
