---
- name: Disable UFW (Ubuntu/Debian)
  systemd:
    name: ufw
    enabled: false
    state: stopped
  register: service_status
  failed_when:
    - service_status is failed
    - not ('Could not find the requested service' in service_status.msg)
  when:
    - sp_disable_fw is defined and
      sp_disable_fw | bool

- name: Add StorPool ports to firewall - 81,3749,47567/TCP (Ubuntu/Debian)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  ignore_errors: true
  with_items: "{{ sp_fw_ports }}"
  when:
    - sp_disable_fw is defined and
      not sp_disable_fw | bool

- name: Disable ondemand service (Ubuntu)
  systemd:
    name: ondemand
    enabled: false
    state: stopped
  ignore_errors: true
  when:
    - ansible_distribution == 'Ubuntu'
