---
- name: Install python2 on Ubuntu 18.04
  raw: apt-get update && apt-get install -y python
  changed_when: false
  failed_when: false
  register: apt_install_result
  until: apt_install_result is succeeded
  when: '''VERSION_ID="18.04"'' in os_release_lines'

- name: Install python3 on Ubuntu 20.04 and Ubuntu 22.04
  raw: apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get install -y python3
  changed_when: false
  failed_when: false
  register: apt_install_result
  until: apt_install_result is succeeded
  when: '''VERSION_ID="20.04"'' in os_release_lines or ''VERSION_ID="22.04"'' in os_release_lines'
