---
- name: Install python
  block:
    - name: Determine node operating system
      raw: cat /etc/os-release
      register: os_release
      changed_when: false
      failed_when: false

    - include_tasks: ensure_centos.yml
      vars:
        os_release_lines: "{{ os_release }}"
      when: '''ID="centos"'' in os_release.stdout_lines'

    - include_tasks: ensure_debian.yml
      when: '''ID=debian'' in os_release.stdout_lines'

    - include_tasks: ensure_ubuntu.yml
      vars:
        os_release_lines: "{{ os_release }}"
      when: '''ID=ubuntu'' in os_release.stdout_lines'
