---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  tasks: []

- name: Ensure python is installed
  hosts: storpool
  connection: ssh
  gather_facts: false
  become: true
  roles:
    - ensure_python

- name: Prepare environment for StorPool
  hosts: storpool
  gather_subset:
    - 'min'
    - 'virtual'
  roles:
    - 1_prepare
  tags:
    - prerequisites
