---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  tasks: []

- name: Prepare environment for StorPool
  hosts: storpool
  gather_facts: false
  become: true
  tasks:
    - name: Ensure python is installed
      import_role:
        name: ensure_python
    - name: Gather facts
      setup:
        gather_subset:
          - 'min'
          - 'virtual'
    - name: Define common variables
      import_role:
        name: 1_prepare

  tags:
    - prerequisites
