---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  tasks: []

- name: Ensure python is installed
  hosts: storpool
  connection: paramiko_ssh
  gather_facts: false
  become: true
  roles:
    - ensure_python

- name: Prepare environment for StorPool
  hosts: storpool
  connection: paramiko_ssh
  gather_subset:
    - 'min'
    - 'virtual'
  become: true
  tasks:
    - name: Define common variables
      import_role:
        name: 1_prepare

  tags:
    - prerequisites
