---
- name: Setup infrastructure for StorPool
  hosts: storpool
  gather_facts: false
  become: true
  roles:
    - 2_setup-infra
    - add-storpool-repo
    - install-sp-python

  tags:
    - setup-infrastructure
