---
- name: Configure StorPool cgroups
  hosts: storpool
  gather_facts: false
  become: true
  roles:
    - name: configure-cgroups
      vars:
        cg_conf_extra: "{{ sp_cg_conf_extra | default(omit) }}"
        start_cgconfig: "{{ sp_cg_start_cgconfig | default('true') }}"

  tags:
    - setup-cgroups
