---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_7
    image: "centos:7"
    pre_build_image: true
  - name: centos_8
    image: "centos:8"
    pre_build_image: true
  - name: ubuntu_16.04
    image: "ubuntu:16.04"
    pre_build_image: true
  - name: ubuntu_18.04
    image: "ubuntu:18.04"
    pre_build_image: true
  - name: ubuntu_20.04
    image: "ubuntu:20.04"
    pre_build_image: true
  - name: debian
    image: "debian:9"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
